import Head from "next/head";
import Link from "next/link";

import days from "../days";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Théo's Genuary 2022</h1>

        <div className="flex flex-col">
          {days.map(({ path, name }) => (
            <Link href={"/[day]"} as={`/${path}`} key={path}>
              <a>{name}</a>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
}
