import Head from "next/head";
import Link from "next/link";

import days from "../days";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Théo's Genuary 2022</h1>

        <p>
          big fan of generative art for a while, first hands on experience.
          learning p5js.
        </p>

        <ul className="flex flex-col mt-8">
          {days.map(({ path, name, comment }) => (
            <Link href={"/[day]"} as={`/${path}`} key={path}>
              <a className="flex space-x-2">
                <span className="text-blue-500 hover:text-blue-300 underline">
                  {name}
                </span>
                <span className="truncate text-gray-400 -underline">
                  {comment}
                </span>
              </a>
            </Link>
          ))}
        </ul>

        <p className="text-xs mt-16">
          <a href="https://github.com/theo-m/genuary">source</a>
        </p>
      </main>
    </div>
  );
}
