import Head from "next/head";
import Link from "next/link";

import days from "../days";

export default function Home() {
  return (
    <div>
      <Head>
        <title>{`Théo's 2022 genuary`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="max-w-md p-8 mx-auto h-screen flex flex-col">
        <h1>
          Théo's{" "}
          <a
            className="font-mono text-blue-500 hover:text-blue-300 underline"
            href="https://genuary.art"
          >
            2022 genuary
          </a>
        </h1>

        <p>
          I like generative art*, this is my first experience doing genuary. The
          sources are available**, I've cobbled together p5js and nextjs.
        </p>

        <ul className="flex flex-col mt-8">
          {days.map(({ id, name, comment, official }) => (
            <Link href={"/[day]"} as={`/${id}`} key={id}>
              <a
                className={
                  "flex space-x-2 text-gray-400" +
                  (official ? " mt-2" : " text-sm")
                }
              >
                <span>{official ? "⬘" : "......"}</span>
                <div className="text-blue-500 hover:text-blue-300 underline whitespace-nowrap">
                  {name}
                </div>
                <div className="truncate">{comment}</div>
              </a>
            </Link>
          ))}
        </ul>

        <p className="text-sm mt-auto">
          [*] I'm keeping a twitter list{" "}
          <a
            className="text-blue-500 hover:text-blue-300 underline"
            href="https://twitter.com/i/lists/1229843989060255745"
          >
            here
          </a>
          .
        </p>

        <p className="text-sm mt-2">
          [**]{" "}
          <a
            className="text-blue-500 hover:text-blue-300 underline"
            href="https://github.com/theo-m/genuary"
          >
            sources
          </a>{" "}
          (with reading notes)
        </p>
      </main>
    </div>
  );
}
